apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVSCtOdjR4R3BndzVoNHNlWTUyemlYMVN5MDFZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSTBNRGd5T1RFNE5USXlORm9YRFRJME1Ea3lPREU0TlRJeU5Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXcxTjhTWkpJdjUxZDhjYWZ2Qi9PNSs4SmxwSlVRbXdWczRGZAptUldQeDU1alI2dTRTdmcrK2VJekNQbXZIbXcwQUtwVnRyQ3c5QVF2QUZSVFBuQmJFNURZSmNOTnZtTDVPRytQClpSekpnMXl4Y2ZhUlFOWWR1VmY0d1YrZnc5eGNkVExRdWRaeWJPOGFScmt3RlJPM2lBYTM0bElwYkh1bEtjcnMKRy84NCtEV2xDVzUreTJJUTRTNUtWOWNoU1hSKzNNSW13M2NwcGxkQzZuYWNudUVGSUdxbVdDcHFqclo1Q2l1dQpaT3RKMkN4K09pY2syVnJrOVBPSnRxYjN3OXpvRHIwYTNDYWVkT04xZzFkdDRxeEVUeTV6QTZyejVFVVBsaVY2Ci8ydVdWSWh6Wm9sNjVGTEJYWTQyMFNsMWlCeDVwYk9wbnZ6V0ErUDZPRGRXdkdhbUx3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVWjgwaWxiZkRhVmpiSEN6MkFKRzdVY0hadHVFd0h3WURWUjBqQkJnd0ZvQVVaODBpbGJmRAphVmpiSEN6MkFKRzdVY0hadHVFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFEL0hwYTJTY2Z5djdCVEplbnBGZGtqWTY1dExYZ09HU1BZREJyMlVESHhibGE0V091eThVZDRTNXdyTjIKT1M0dTBEZm1pRU01Ny9tUWM1RVNSQ3N5SDcweEZzZnl5NEM5dnZySjhMMmVnUFNLMEpmc1JmaTdWVzN3UWpoVQpISml3cmRqa3VtZHdCOVl5NVloRHloYmJKUTYxd3BSaGlDMDFhVzVBRFg4MmhTQS93anBodFpTa3pKWndZVVV3CmJKU3NSYlpxbGVDenJPWWMvc0ozQzR1SHI3UnNXZ0UxdFJJSzBXSmdOLzVKYXlHYzlHcHQ0YjFOdGN6TW1WTm0KUWkwMVdTdGdkUW4ydW10QTl6S25aS0ltMmRyajZBdnE1SFErU0xJNHhpOEJLUWpOdHdVUXNPYWovZHpNN1h5RApibHlQcUFBeStPcXNwU2FrcTlHRW1oZXFXZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None