apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
     claimName: local-pvc
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - mountPath: "/var/www/html"
      name: pv-volume